name: "GitHub Classroom Autograding Results handler"
description: "Integrate your CS class with GitHub using GitHub Classroom"
inputs:
  token:
    description: >
      GitHub token used to check repository content and provide feedback. By default, 
      this uses the repository token provided by GitHub Actions. You can customize this
      by replacing this token with a user token which has write-access to your repository. 
      Note that the token will be accessible to all repository collaborators.
    default: ${{ github.token }}
  runners:
    description: 'Comma-separated list of step ids'
    required: true

runs:
  using: "node20"
  main: 'dist/reporter-grader/main.js'